### ISSUE TITLE
Transfer to ITensor organization

### ISSUE THREAD

**Issue by mtfishman** [ITensor/Observers.jl#23]
@GTorlai can you transfer this repository to the ITensor organization? It will make it easier for us to develop, we're starting to use it more and more in various ITensor libraries.

**Comment by GTorlai** [comment]
I tried but looks like I don't have permission. Can you add me to the organization and allow me to create a report in it?

**Comment by mtfishman** [comment]
Sure, just invited you.

**Comment by GTorlai** [comment]
Done

**Comment by mtfishman** [comment]
Thanks!
